### ISSUE TITLE
dates for festivals

### ISSUE THREAD

**Issue by hannesdatta** [course-dprep/Influence-of-festivals-on-Airbnb-prices#4]
__Motivation__

For our RQ, we need broad coverage of festivals. 

__Deliverable__

- A dataset with festival names and dates when festivals occurred

**Comment by Kansu1** [comment]
Mardi Gras 23 February - 1 March 2022
French Quarter Festival 21 April - 24 April 2022
New Orleans Jazz & Heritage Festival 29 April - 8 May 2022
